name: Manual Pre Release Publish

on:
  workflow_dispatch:
    inputs:
      release_candidate_suffix:
        description: 'RC Suffix e.g. rc0, beta1, alpha2. Do not include a leading hyphen.'
        required: true
        type: string

concurrency:
  group: deploy
  cancel-in-progress: false  # prevent hickups with semantic-release

env:
  PYTHON_VERSION_DEFAULT: "3.11"
  POETRY_VERSION: "1.4.1"
  PY_SEMVER_RELEASE_VERSION: "7.33.2"

jobs:
  release_candidate:
    runs-on: ubuntu-latest
    concurrency: release_candidate
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION_DEFAULT }}
      - name: Install dependencies
        run: |
          python -m pip install poetry=="$POETRY_VERSION" --upgrade pip
          poetry config virtualenvs.create false
          poetry install
          python -m pip install python-semantic-release=="$PY_SEMVER_RELEASE_VERSION"
      - name: Apply Pre Release Version
        run: |
          RC_VERSION="$(semantic-release --noop --major print-version)-${{ github.event.inputs.release_candidate_suffix }}"
          echo "RC Version will be: ${RC_VERSION}"
          poetry version "${RC_VERSION}"
          poetry build
      - name: Publish Pre Release 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TOKEN }}
