name: Manual Release Candidate

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to produce Release Candidate from'
        required: true
        type: string
      rc_number:
        description: 'RC Number'
        default: 0
        required: true
        type: number

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install poetry --upgrade pip
          poetry config virtualenvs.create false
          poetry install
          python -m pip install python-semantic-release
      - name: Determine RC candidate version
        run: |
          RC_VERSION="$(python-semantic-release --noop --major print-version)rc${{ inputs.rc_number }})"
          echo "RC Version will be: ${RC_VERSION}"
#      - name: Python Semantic Release
#        uses: relekang/python-semantic-release@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          pypi_token: ${{ secrets.PYPI_TOKEN }}